---
- name: Create and configure the awx inventory, hosts and organization
  block:
  - name: "Add the organization"
    awx.awx.organization:
      name: "{{ awx_organization }}"
      controller_host: "{{awx_controller_protocol}}://{{awx_controller_host}}"
      controller_username: "{{awx_controller_username}}"    
      controller_password: "{{awx_controller_password}}"
      state: "present"

  - name: "Add/check the inventory"
    awx.awx.inventory:
      name: "{{ awx_inventory_name }}"
      description: "k8s cluster servers"
      organization: "{{ awx_organization }}"
      controller_host: "{{awx_controller_protocol}}://{{awx_controller_host}}"
      controller_username: "{{awx_controller_username}}"    
      controller_password: "{{awx_controller_password}}"
      state: "present"
    
  - name: "Add the workers and masters nodes"
    awx.awx.host:
      name: "{{ item }}"
      description: "Kubernetes"
      inventory: "{{ awx_inventory_name }}"
      controller_host: "{{awx_controller_protocol}}://{{awx_controller_host}}"
      controller_username: "{{awx_controller_username}}"    
      controller_password: "{{awx_controller_password}}"
      state: "present"
    with_items: "{{ hcloud_workers | union(hcloud_masters) }}"

  - name: "Add the host to the worker group"
    awx.awx.group:
      name: "{{awx_group_nodes}}"
      hosts: "{{ hcloud_workers }}"
      inventory: "{{ awx_inventory_name }}"
      controller_host: "{{awx_controller_protocol}}://{{awx_controller_host}}"
      controller_username: "{{awx_controller_username}}"    
      controller_password: "{{awx_controller_password}}"
      state: "present"

  - name: "Add the host to the master group"
    awx.awx.group:
      name: "{{awx_group_master}}"
      hosts: "{{ hcloud_masters }}"
      inventory: "{{ awx_inventory_name }}"
      controller_host: "{{awx_controller_protocol}}://{{awx_controller_host}}"
      controller_username: "{{awx_controller_username}}"    
      controller_password: "{{awx_controller_password}}"
      state: "present"
  when: "awx_controller_username is defined and awx_controller_password is defined and awx_controller_host is defined and awx_controller_protocol is defined"

